#pragma once

// Domain types describing a single entry inside an opened WAD.
//
// `WadAssetName` is the decomposed asset-name parser used by the GOWR
// node builder; `AssetEntry` is the tree node both profiles produce
// after they walk a WAD. M1.T1 extracted these out of the monolithic
// `core/WadTypes.h` umbrella so consumers can depend on them in
// isolation. The umbrella is still around for transitional reasons.

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "core/domain/MediaKind.h"
#include "core/domain/ProfileTag.h"
#include "core/schema/AssetNode.h"
#include "core/types/GameVersion.h"
#include "core/types/TypeId.h"

// NOTE: `WadAssetName` and `AssetEntry` live at global scope to match
// the legacy layout in `core/WadTypes.h`. They reference `Onyx::TypeId`
// and `Onyx::AssetNode` by qualified name. They will move into the
// `Onyx::` namespace in a later milestone alongside the schema-string
// retirement.

// ── WadAssetName ──────────────────────────────────────────────────────────────
// Parses a FileDesc name from the Ragnarök WAD in the format:
//   PREFIX_baseName_lodIndex_variant---wadIndex.bin
//
// Examples:
//   "MG_heroa00_0_gpu---12389"   -> prefix="MG",  base="heroa00",  lod=0, variant="gpu",  wadIndex=12389
//   "ANM_heroa00---10397"        -> prefix="ANM", base="heroa00",  lod=-1, variant="",    wadIndex=10397
//   "autopad---10399"            -> prefix="",    base="autopad",  lod=-1, variant="",    wadIndex=10399
//   "DCClientGUID---13956"       -> prefix="",    base="DCClientGUID", lod=-1, variant="",wadIndex=13956
//   "a41955a3abdbf109_ps_30000207---2447" -> prefix="", base="a41955a3abdbf109", lod=-1, variant="ps_30000207", wadIndex=2447
//
// The wadIndex is the sequential FileDesc index inside the WAD (field after "---").
// It is NOT a hash — just the insertion position used for debug/extraction.
//
// The "---" separator + number is generated by the export tool, not read back by the engine.
struct [[deprecated("use profiles/gowr/GowrTaxonomy.h")]] WadAssetName {
    std::string prefix;     // "MG", "ANM", "PEM", "GOWR_SHADER", "" (empty = no prefix)
    std::string base;       // asset name: "heroa00", "DCClientGUID", "autopad"
    int         lod  = -1;  // LOD index (>= 0 if present), -1 = no LOD
    std::string variant;    // "gpu", "cpu", "ps", "ps_30000207", "" = no variant
    int         wadIndex = -1; // sequential FileDesc index (number after "---")

    // Returns true if the name was successfully parsed from a raw string.
    // The raw field does NOT include the ".bin" extension — pass only the stem.
    static WadAssetName Parse(const std::string& raw);

    // Group key: joins prefix + base to group variants/LODs of the same asset.
    // E.g.: "MG_heroa00_0_gpu" and "MG_heroa00_0_cpu" -> groupKey = "MG|heroa00"
    std::string GroupKey() const {
        return prefix.empty() ? base : (prefix + "|" + base);
    }

    // Reconstructs the canonical name without the wadIndex (as the engine sees the asset).
    std::string CanonicalName() const;

    // Returns true if this is a GPU variant (needs lodpack for vertex data).
    bool IsGpuVariant()  const { return variant == "gpu"; }
    // Returns true if this is a PS4/PS5 shader (name is a hex hash).
    bool IsShader()      const { return variant.find("ps") != std::string::npos ||
                                        variant.find("vs") != std::string::npos; }
    // Returns true if this is an internal entry with no asset semantics (autopad, PopHeap, etc.).
    bool IsInternal()    const { return prefix.empty() && lod < 0 && variant.empty(); }
};

// ── AssetEntry ──────────────────────────────────────────────────────────────
// One node in the parsed WAD tree. Profiles populate this; the inspector
// UI and the test snapshot harness both read it.
struct AssetEntry {
    std::string           name;
    std::string           wadName;
    uint32_t              size = 0;
    uint32_t              offset = 0;
    uint64_t              hash = 0;

    // Compiled type identifier
    Onyx::TypeId           typeId = {};

    // Child nodes for UI tree
    std::vector<AssetEntry> children;

    // Loaded data (on demand)
    std::shared_ptr<Onyx::AssetNode> assetNode;

    Onyx::MediaKind kind       = Onyx::MediaKind::Unknown;
    Onyx::ProfileTag profileTag;
    std::string   displayName;   // human-friendly name (falls back to name if empty)
};
